name: check, build, deploy carpentries.org

on:
  push:
    branches: main
  pull_request: []
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build-website:
    if: github.repository_owner == 'carpentries'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Set up Ruby
        uses: actions/setup-ruby@main
        with:
          ruby-version: '2.7.1'

      - name: Install GitHub Pages, Bundler, and kramdown gems
        run: |
          gem install bundler

      - name: Checkout the lesson
        uses: actions/checkout@master

      - name: Get GeoJSON for instructor map
        run: |
           curl --remote-name-all https://feeds.carpentries.org/all_instructors_by_airport.geojson &&\
           cp all_instructors_by_airport.geojson files/.

      - name: Build site
        run: make install && make site

      - name: Deploy to AWS
        id: deploy
        uses: fmichonneau/s3-sync-action@log-output
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: _site/

      - name: identify files to invalidate
        run: |
          echo "${{ steps.deploy.outputs.action_log }}" > log.txt && grep 'upload: ' log.txt  | awk '{gsub("_site", "");print $3 }' > .updated_files && cat .updated_files



      # - name: invalidate cache
      #   uses: chetan/invalidate-cloudfront-action@master
      #   env:
      #     PATHS_FROM: .updated_files
      #     AWS_REGION: 'us-east-1'
      #     DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
