name: check, build, deploy carpentries.org

on:
  push:
    branches: main
  pull_request: []
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build-website:
    if: github.repository_owner == 'carpentries'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Set up Ruby
        uses: actions/setup-ruby@main
        with:
          ruby-version: '2.7.1'

      - name: Install GitHub Pages, Bundler, and kramdown gems
        run: |
          gem install bundler yaml-lint

      - name: Set up caching for Bundler
        uses: actions/cache@v2
        with:
          path: .vendor/bundle
          key: gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            gems-

      - name: Checkout the Repository
        uses: actions/checkout@master

      - name: Get GeoJSON for instructor map
        run: |
           curl --remote-name-all https://feeds.carpentries.org/all_instructors_by_airport.geojson &&\
           cp all_instructors_by_airport.geojson files/.

      - name: Lint _config.yml with yaml-lint
        run: |
          yaml-lint  _config.yml

      - name: Lint pages and blog posts
        run: |
          yaml-lint -q -n $(find _posts -regex ".*.md\|.*html") &&\
          yaml-lint -q -n $(find pages -regex ".*.md\|.*html")

      - name: Install & Update Ruby Gems
        run: |
          bundle config path .vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle update

      - name: Create dir to store previous version
        run: mkdir _site_prev

      - name: Get current version from S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: _site_prev/

      - name: list content of previous version
        run: ls -R _site_prev/

      - name: Build site
        run: make site

      - name: Deploy to AWS
        id: deploy
        uses: fmichonneau/s3-sync-action@log-output
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: _site/

      - name: identify files to invalidate
        uses: fmichonneau/ga-compare-folders@main
        with:
          path_1: _site_prev/
          path_2: _site/
          out: changed_files.txt

      - name: check output
        run: cat changed_files.txt


      # - name: invalidate cache
      #   uses: chetan/invalidate-cloudfront-action@master
      #   env:
      #     PATHS_FROM: .updated_files
      #     AWS_REGION: 'us-east-1'
      #     DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
